Repository jboss-container-images/rhpam-7-image, pull requests merged in 2020-11, with the labels that each got.

#429 Add Kaitou to default reviewers
  .github/bot-files/reviewers.yml
Labels: needs review :mag:

#415 [AF-2626] - Create Dashbuilder Runtime Image
  .circleci/config.yml
  dashbuilder/README.adoc
  dashbuilder/modules/dashbuilder/install
  dashbuilder/modules/dashbuilder/module.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#437 [KIECLOUD-453] - Adapt product artifacts definitions to CPaaS build
  README.md
  businesscentral-monitoring/modules/businesscentral-monitoring/module.yaml
  businesscentral/modules/businesscentral/module.yaml
  controller/modules/controller/module.yaml
  dashbuilder/modules/dashbuilder/module.yaml
  kieserver/modules/kieserver/module.yaml
  process-migration/modules/process-migration/module.yaml
  smartrouter/modules/smartrouter/module.yaml
Labels: master ⇨ 7.10.0, needs review :mag:

#438 [KIECLOUD-453] -Adapt product artifacts definitions to CPaaS build
  README.md
  businesscentral-monitoring/modules/businesscentral-monitoring/module.yaml
  businesscentral/modules/businesscentral/module.yaml
  controller/modules/controller/module.yaml
  kieserver/modules/kieserver/module.yaml
  process-migration/modules/process-migration/module.yaml
  smartrouter/modules/smartrouter/module.yaml
Labels: ready 🚀

#447 [KIECLOUD-467] - Prepare RHDM and RHPAM 7.9.x branches for 7.9.1 release
  README.md
  businesscentral-monitoring/modules/businesscentral-monitoring/module.yaml
  businesscentral/modules/businesscentral/module.yaml
  controller/modules/controller/module.yaml
  kieserver/modules/kieserver/module.yaml
  process-migration/modules/process-migration/module.yaml
  smartrouter/modules/smartrouter/module.yaml
Labels: 7.9.x ⇨ 7.9.1, needs review :mag:
