Repository jboss-container-images/rhpam-7-image, pull requests merged in 2021-06, with the labels that each got.

#505 Applying RHPAM CR build CR2
  kieserver/modules/kieserver/module.yaml
Labels: needs review :mag:

#507 [KIECLOUD-542] Conscious Language on KieCloud repos
  README.md
Labels: master ⇨ 7.12.0

#509 [KIECLOUD] - Standardize logging script import in Smartrouter and PIM…
  process-migration/modules/process-migration/module.yaml
  smartrouter/modules/smartrouter/module.yaml
Labels: master ⇨ 7.12.0, ready 🚀
