Repository jboss-container-images/rhpam-7-image, pull requests merged in 2021-07, with the labels that each got.

#496 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator -7.11.x
  kieserver/modules/kieserver/module.yaml
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#497 [RHPAM-3640] Configure Kafka JBPM Emitter from Operator
  kieserver/modules/kieserver/module.yaml
Labels: master ⇨ 7.12.0, ready 🚀

#516 [KIECLOUD-551] - Prepare RHPAM and RHDM for 7.11.1 release
  README.md
  businesscentral-monitoring/modules/businesscentral-monitoring/module.yaml
  businesscentral/modules/businesscentral/module.yaml
  controller/modules/controller/module.yaml
  dashbuilder/modules/dashbuilder/module.yaml
  kieserver/modules/kieserver/module.yaml
  process-migration/modules/process-migration/module.yaml
  smartrouter/modules/smartrouter/module.yaml
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#518 [KIECLOUD-549] - Adjust permissions on rhpam/dm-7-kieserver module
  kieserver/modules/kieserver/install
Labels: main ⇨ 7.12.0, ready 🚀

#520 [KIECLOUD-556] - Adjust permissions on rhpam/dm base module workbench
  businesscentral/modules/businesscentral/install
Labels: main ⇨ 7.12.0, ready 🚀

#522 [KIECLOUD-558] - Adjust permissions on rhpam/dm base module controller
  controller/modules/controller/install
Labels: main ⇨ 7.12.0, ready 🚀

#523 [KIECLOUD-559] - Adjust permissions on rhpam dashbuilder base module
  dashbuilder/modules/dashbuilder/install
Labels: main ⇨ 7.12.0, ready 🚀

#524 [RHPAM-3805] - Missing kie dependencies in Kie Server ocp image
  kieserver/modules/kieserver/install
  kieserver/modules/kieserver/module.yaml
Labels: 7.11.x ⇨ 7.11.1, ready 🚀

#525 [RHPAM-3805] - Missing kie dependencies in Kie Server ocp image (#524)
  kieserver/modules/kieserver/install
  kieserver/modules/kieserver/module.yaml
Labels: main ⇨ 7.12.0, ready 🚀
